ALTER TABLE fit_tracker.member
    ALTER COLUMN weight TYPE DOUBLE PRECISION,
    ALTER COLUMN weight_goal TYPE DOUBLE PRECISION,
    ALTER COLUMN body_fat TYPE DOUBLE PRECISION;

ALTER TABLE fit_tracker.member_aud
    ALTER COLUMN weight TYPE DOUBLE PRECISION,
    ALTER COLUMN weight_goal TYPE DOUBLE PRECISION,
    ALTER COLUMN body_fat TYPE DOUBLE PRECISION;
