server:
  port: 8080
  error:
    include-message: always

management:
  endpoints:
    web:
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
        exposed-headers: "*"
      exposure:
        include: "health,info"

s3:
  region:
    name: us-east-1
  bucket:
    name: fitness-tracker-customers

spring:
  datasource:
    username: postgres
    password: root1234
    url: jdbc:postgresql://localhost:5432/robinsonir
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      org:
        hibernate:
          envers:
            default_schema: fit_tracker
    show-sql: true
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  config:
    import: optional:file:.env[.properties]
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB
  data:
    jdbc:
      repositories:
        enabled: off
logging:
  level:
    org.springframework: debug
    com.robinsonir.fitnesstracker: debug
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"  # Pattern for console logs

