server:
  port: 8080
  error:
    include-message: always

management:
  endpoints:
    web:
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
        exposed-headers: "*"
      exposure:
        include: "health,info"

s3:
  region:
    name: us-east-1
  bucket:
    name: fitness-tracker-customers

spring:
  datasource:
    username: postgres
    password: root1234
    url: jdbc:postgresql://localhost:5432/robinsonir
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: fit_tracker
    show-sql: true
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  config:
    import: optional:file:.env[.properties]
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB
  data:
    jdbc:
      repositories:
        enabled: off
logging:
  level:
#    org.springframework: DEBUG
    com.robinsonir.fittrack: DEBUG
    org.hibernate.envers.boot: WARN
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web: DEBUG   # Logs incoming web requests
    org.springframework.web.client.RestTemplate: DEBUG   # Logs outbound API calls
    org.springframework.web.servlet: DEBUG   # Logs servlet details
    org.springframework.cloud.openfeign: WARN  # Change to DEBUG if debugging Feign
    feign.Logger: WARN   # Change to DEBUG if debugging Feign
    org.springframework.security: WARN   # Change to DEBUG if debugging auth
    org.springframework.security.web: WARN
    org.springframework.cache: WARN
    org.springframework.client.discovery: WARN
    org.springframework.cloud.consul: WARN
    org.springframework.cloud.sleuth: WARN
    org.springframework.core.convert: WARN
    org.springframework.format: WARN
    org.springframework.retry: WARN
    org.springframework.web.client: WARN
    org.springframework.ws: WARN
    sun.net.www.protocol: WARN
