name: CI - Application Build

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read

env:
  POSTGRESQL_VERSION: 15
  POSTGRESQL_DB: fit-tracker
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: root1234
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'liberica'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.6.1

      - name: Create fit_tracker schema
        run: |
          echo "CREATE SCHEMA IF NOT EXISTS fit_tracker;" | PGPASSWORD=${{ env.POSTGRESQL_PASSWORD }} psql -h localhost -U ${{ env.POSTGRESQL_USER }} ${{ env.POSTGRESQL_DB }}
      - name: Install React dependencies
        run: cd ./fit-track-ui/react && npm ci

      - name: Run ESLint
        run: cd ./fit-track-ui/react && npm run lint

      - name: Build with Gradle
        run: gradle build