name: CD - Frontend


on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - fit-track-ui/react/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for changes in fit-track/ directory
        id: check-changes
        run: |
          if git diff --quiet HEAD^ HEAD -- fit-track/; then
            echo "No changes detected in fit-track/"
            echo "skip_wait=true" >> $GITHUB_ENV
          else
            echo "Changes detected in fit-track/"
            echo "skip_wait=false" >> $GITHUB_ENV
          fi
      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"
      - name: Docker Login
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build the Docker image
        run: |
          docker build fit-track-ui \
          --file fit-track-ui/Dockerfile \
          --tag ${{secrets.DOCKER_HUB_USERNAME}}/robinsonir-react:${{steps.build-number.outputs.BUILD_NUMBER}} \
          --build-arg api_base_url=http://robinsonir-api-env.eba-aebgw6jr.us-east-1.elasticbeanstalk.com/8080
      - name: Publish docker image to docker hub
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/robinsonir-react:${{steps.build-number.outputs.BUILD_NUMBER}}
      - name: Build Docker image with latest tag
        run: |
          docker build fit-track-ui \
          --file fit-track-ui/Dockerfile \
          --tag ${{secrets.DOCKER_HUB_USERNAME}}/robinsonir-react:latest \
          --build-arg api_base_url=http://fitness-tracker-env.eba-3f5efq3k.us-east-1.elasticbeanstalk.com:8080
      - name: Publish docker image to docker hub
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/robinsonir-react:latest
      - name: Wait 80 for Elastic Beanstalk status
        if: env.skip_wait == 'false'
        run: |
          echo "Waiting 120 seconds for Elastic Beanstalk status"
          sleep 120  # Wait for 120 seconds
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: ${{ github.SHA }}
          region: ${{ secrets.EB_REGION }}
          deployment_package: Dockerrun.aws.json
          wait_for_environment_recovery: 60
